SET foreign_key_checks = 0;
INSERT INTO `category` (id,name,slug) VALUES ("1","Уборка","clean");
INSERT INTO `category` (id,name,slug) VALUES ("2","Компьютерная помощь","neo");
INSERT INTO `category` (id,name,slug) VALUES ("3","Ремонт квартирный","flat");
INSERT INTO `category` (id,name,slug) VALUES ("4","Ремонт техники","repair");
INSERT INTO `category` (id,name,slug) VALUES ("5","Красота","beauty");
INSERT INTO `category` (id,name,slug) VALUES ("6","Фото","photo");
INSERT INTO `category` (id,name,slug) VALUES ("7","Переводы","translation");
INSERT INTO `category` (id,name,slug) VALUES ("8","Переезды","cargo");
SET foreign_key_checks = 1;