SET foreign_key_checks = 0;
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("1","1","2");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("2","3","4");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("3","2","1");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("4","5","4");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("5","1","3");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("6","4","6");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("7","5","2");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("8","9","1");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("9","7","8");
INSERT INTO `task_category` (id,task_id,category_id) VALUES ("10","7","3");
SET foreign_key_checks = 1;